[[headers]]
  for = "/*.js"
  [headers.values]
    Content-Type = "text/javascript"
[[headers]]
  for = "/*.jsx"
  [headers.values]
    Content-Type = "text/javascript"

[build]
  base = ""
  command = "npm install && npm run build"
  publish = "dist"